### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by PadraAx** [OCA/l10n-iran#27]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "F:\odoo_siegel_tetst\server\odoo\http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "F:\odoo_siegel_tetst\server\odoo\service\model.py", line 134, in retrying
    result = func()
  File "F:\odoo_siegel_tetst\server\odoo\http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "F:\odoo_siegel_tetst\server\odoo\http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "F:\odoo_siegel_tetst\server\odoo\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "F:\odoo_siegel_tetst\server\odoo\addons\base\models\ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "F:\odoo_siegel_tetst\server\odoo\http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "F:\odoo_siegel_tetst\server\odoo\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "F:\odoo_siegel_tetst\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "F:\odoo_siegel_tetst\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "F:\odoo_siegel_tetst\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "F:\odoo_siegel_tetst\server\odoo\addons\base\models\ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "F:\odoo_siegel_tetst\server\odoo\addons\base\models\ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "F:\odoo_siegel_tetst\server\odoo\addons\base\models\ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "F:\odoo_siegel_tetst\server\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "F:\odoo_siegel_tetst\server\odoo\modules\registry.py", line 91, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "F:\odoo_siegel_tetst\server\odoo\modules\loading.py", line 484, in load_modules
    loaded_modules, update_module, models_to_check)
  File "F:\odoo_siegel_tetst\server\odoo\modules\loading.py", line 373, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "F:\odoo_siegel_tetst\server\odoo\modules\loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "F:\odoo_siegel_tetst\server\odoo\modules\loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "F:\odoo_siegel_tetst\server\odoo\tools\convert.py", line 759, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "F:\odoo_siegel_tetst\server\odoo\tools\convert.py", line 805, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_ir_states failed: file l10n_ir_states\data/res.country.state.csv could not be processed:
 The values for the fields 'country_id, code' already exist (they are probably 'Country, State Code' in the current model).

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/794-16de89e/web.assets_backend.min.js:967:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/794-16de89e/web.assets_backend.min.js:974:13)

**Comment by saeed-raeisi** [comment]
Check out
Duplicate country_id is not entered
